name: "デプロイ実行権限を持つUser"
description: "デプロイ実行権限を持つUserを管理する"
outputs:
  is-deploy-user:
    description: "実行者がデプロイ権限をもつユーザーか判定する"
    value: ${{ steps.check-deploy-user.outputs.is-deploy-user }}
runs:
  using: composite
  steps:
    - id: check-deploy-user
      env:
        DEPLOY_USERS: '["user1", "user2", "user3", "msgyu"]'
      run: echo "is-deploy-user=${{ contains(env.DEPLOY_USERS, github.actor) }}" >> $GITHUB_OUTPUT
      shell: bash
    # 下記は実行を試みたができないもの
    # - run: |
      #   echo exe-user: ${{ inputs.is-deploy-user }}
      #   echo exe-user: ${{ env.DEPLOY_USERS }}
      # run: echo "is-deploy-user=${{ contains(env.DEPLOY_USERS, msgyu }} }}" >> $GITHUB_OUTPUT
      #   echo "is-deploy-user=${{ contains(env.DEPLOY_USERS, inputs.exe-user }} }}" >> $GITHUB_OUTPUT


