name: Hello World
run-name: Hello World ${{ github.actor }}
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: "挨拶をする"
    steps:
      - uses: actions/checkout@v4
      - id: hello
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: "${{ github.actor }}"
      - run: echo random-number ${{ steps.hello.outputs.random-number }} # steps.{id}.outputs.取得したい値
        shell: bash
