name: "if文について学習する"
run-name: "${{ github.actor }} はif文を学習しました"
on: [push]
jobs:
  if-study:
    if: github.repository == 'msgyu/quick-start-github-actions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
  if-boolean-false:
    if: true && false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo true
  if-boolean-true:
    # 式構文 ${{ }} を使用すると、内容が文字列に変わり、文字列は真値です。
    if: true && ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo true
  ternary-operator:
    env:
      # 三項演算子を使用すると、簡単に条件分岐ができます。 @see https://docs.github.com/ja/actions/learn-github-actions/expressions
      # 条件 && 真値 || 偽値
      MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo $MY_ENV_VAR
  study-contains-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo `lloはhellow worldに含まれますか？ ${{ contains('Hello world', 'llo') }}`
      - run: echo ` ${{ contains(github.event.issue.labels.*.name, 'bug') }}`
      - run: echo  `eventはpushまたはpull_requestですか${{ contains(fromJSON('["push", "pull_request"]'), github.event_name)}}` # github.event_name == "push" || github.event_name == "pull_request"とは別の表現
      - run: echo `toJSON中身を確認する。 ${{ toJSON(github.event) }}`
  study-fromJSON:
    runs-on: ubuntu-latest
    env:
      continue: true
      time: 3
    steps:
      - continue-on-error: ${{ fromJSON(env.continue) }} # ステップが失敗したときにジョブが失敗するのを防ぎます。このステップが失敗した場合にジョブを通過できるようにするには、trueに設定します。
        timeout-minutes: ${{ fromJSON(env.time) }}
        run: echo ...
      - run: echo ${{ env.continue }}
      - run: echo ${{ fromJSON(env.continue) }} # 環境変数を文字列からブール値もしくは整数に変換します。
      - run: echo ${{ env.time }}
      - run: echo ${{ fromJson(env.time) }} # 環境変数を文字列からブール値もしくは整数に変換します。
  study-array:
    runs-on: ubuntu-latest
    env:
      fruits: '[{ "name": "apple", "quantity": 1 }, { "name": "orange", "quantity": 2 }, { "name": "pear", "quantity": 1 }]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Fruits Array
        run: |
          fruits_json='${{ env.fruits }}'
          for row in $(echo "${fruits_json}" | jq -c '.[]'); do
            name=$(echo $row | jq -r '.name')
            quantity=$(echo $row | jq -r '.quantity')
            echo "Fruit: $name, Quantity: $quantity"
          done
        shell: bash
      - run: echo ${{ env.fruits.*.name }}
      - run: echo ${{ contains(env.fruits.*.name, 'apple') }}
