name: "他ファイルで定義された配列を取得する"
run-name: "他ファイルで定義された配列を取得する"
on: ["push"]
jobs:
  import-array:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: geti-deploy-users
        id: get-deploy-users
        env:
          DEPLOY_USERS: '["user1", "user2", "user3", "msgyu"]'
        if: ${{ contains(env.DEPLOY_USERS, github.actor) }}
        run: echo "is-deploy-user=true" >> $GITHUB_OUTPUT
      - name: "対象のユーザーかどうかを結果を出力"
        run: |
          echo "is-deploy-user: ${{ steps.get-deploy-users.outputs.is-deploy-user }}"
