name: "他ファイルで定義された配列を取得する"
run-name: "他ファイルで定義された配列を取得する"
on: ["push"]
jobs:
  import-array:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get-deploy-users
        id: get-deploy-users
        env:
          DEPLOY_USERS: '["user1", "user2", "user3", "msgyu"]'
        run: echo "is-deploy-user=${{ contains(env.DEPLOY_USERS, github.actor) }}" >> $GITHUB_OUTPUT
      - name: "対象のユーザーかどうかを結果を出力"
        run: echo "is-deploy-user is  ${{ steps.get-deploy-users.outputs.is-deploy-user }}"
      - name: "デプロイユーザーならデプロイする"
        if: ${{ steps.get-deploy-users.outputs.is-deploy-user == true }}
        run: echo deploy!!
