name: "変数の理解を深める"
run-name: "${{github.actor}}は変数の理解を深めています"
on:
  push:
    branches:
      - main
jobs: # 変数はsecrets, vars, github, runnner, env, outputsで定義されている
  job1:
    runs-on: ubuntu-latest
    # 他のJOBで参照できるようにGITHUB_OUTPUTを定義
    outputs:
      output1: ${{ steps.step1.outputs.test }} # stepsで定義したstep1の結果を参照
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Set the value
        id: step_one
        run: echo "action_state=yellow" >> "$GITHUB_ENV" # GITHUB_ENVは他のStepで参照できるようになる。他のJOBでは参照できない。
      - name: Use the value
        id: step_two
        run: printf '%s\n' "$action_state" # GITHUB_ENVで定義した変数を参照
      - id: step0
        run: echo "{environment_variable_name}={value}" >> "$GITHUB_ENV"
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT" # 他のJOBで参照できるようにGITHUB_OUTPUTに出力
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1 # job1の結果を待つ
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}} # needs.job1でjob1の結果を参照
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
